---
- name: Download AlmaLinux ISO and Verify SHA256 Checksum
  hosts: localhost
  gather_facts: no

  vars:
    ks_iso_url: "https://repo.almalinux.org/almalinux/9.3/isos/x86_64/AlmaLinux-9.3-x86_64-dvd.iso"
    destination: "/path/to/destination/AlmaLinux-9.3-x86_64-dvd.iso"
    expected_sha256: "a8c4ed4b79edd0977d7f88be7c07e12c4b748671a7786eb636c6700e58068d5"

  tasks:
    - name: Download AlmaLinux ISO
      ansible.builtin.get_url:
        url: "{{ ks_iso_url }}"
        dest: "{{ destination }}"
      async: 3600  # Run for 1 hour
      poll: 0
      register: download_iso

    - name: Wait for the download to complete
      ansible.builtin.async_status:
        jid: "{{ download_iso.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 120  # Retry 120 times
      delay: 30  # Delay of 30 seconds between retries

    - name: Calculate SHA256 checksum of the downloaded file
      ansible.builtin.command:
        cmd: "sha256sum {{ destination }}"
      register: actual_checksum_output
      when: job_result.finished

    - name: Verify SHA256 Checksum
      ansible.builtin.fail:
        msg: "Checksum verification failed"
      when: job_result.finished and (expected_sha256 not in actual_checksum_output.stdout)
