---
- name: Set ks_kickstart_file_path based on kickstart_type
  set_fact:
    ks_kickstart_file_path: "{{ kickstart_file_paths[kickstart_type] }}"

- name: Display ks_kickstart_file_path
  debug:
    msg: "The kickstart file path is {{ ks_kickstart_file_path }}"
